--READ UNCOMMITTED /
--1
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION;

INSERT INTO ShortPricePaidData2025
VALUES ('TEST', 9999999999, GETDATE(), 'XXXX', 'F', 'N', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST');

--3
ROLLBACK



--READ COMMITTED
--2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION

INSERT INTO ShortPricePaidData2025
VALUES ('TEST2', 9999999999, GETDATE(), 'XXXX', 'F', 'N', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST');

COMMIT;

--AFTER TEST

DELETE FROM ShortPricePaidData2025
WHERE TransactionUniqueIdentifier = 'TEST2';



--SERIALIZABLE: PREVENT DIRTY READ
--1
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

BEGIN TRANSACTION;

INSERT INTO ShortPricePaidData2025
VALUES ('TEST', 9999999999, GETDATE(), 'XXXX', 'F', 'N', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST');

--3
ROLLBACK


--SERIALIZABLE: PREVENT UNREPEATABLE READ
--2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION

INSERT INTO ShortPricePaidData2025
VALUES ('TEST2', 9999999999, GETDATE(), 'XXXX', 'F', 'N', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST', 'TEST');

COMMIT;

--AFTER TEST

DELETE FROM ShortPricePaidData2025
WHERE TransactionUniqueIdentifier = 'TEST2';

